
import './style.css';
import React from 'react';

    
const Data = () => {
  return (
    <div className='background'>
        <div className='data'>
      <h2>Satellite Categories</h2>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Satellites/Debris</th>
            <th>Rocket Bodies</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Amateur radio</td>
            <td>875</td>
            <td>1</td>
            <td>897</td>
          </tr>
          <tr>
            <td>Beidou Navigation System</td>
            <td>56</td>
            <td>0</td>
            <td>56</td>
          </tr>
          <tr>
            <td>Brightest</td>
            <td>55</td>
            <td>1</td>
            <td>133</td>
          </tr>
          <tr>
            <td>Celestis</td>
            <td>3</td>
            <td>0</td>
            <td>4</td>
          </tr>
          <tr>
            <td>Chinese Space Station</td>
            <td>12</td>
            <td>0</td>
            <td>12</td>
          </tr>
          <tr>
            <td>CubeSats</td>
            <td>174</td>
            <td>0</td>
            <td>174</td>
          </tr>
          <tr>
            <td>Disaster monitoring</td>
            <td>26</td>
            <td>0</td>
            <td>26</td>
          </tr>
          <tr>
            <td>Earth resources</td>
            <td>141</td>
            <td>0</td>
            <td>141</td>
          </tr>
          <tr>
            <td>Education</td>
            <td>28</td>
            <td>0</td>
            <td>28</td>
          </tr>
          <tr>
            <td>Engineering</td>
            <td>63</td>
            <td>0</td>
            <td>63</td>
          </tr>
          <tr>
            <td>Experimental</td>
            <td>147</td>
            <td>0</td>
            <td>147</td>
          </tr>
          <tr>
            <td>Flock</td>
            <td>135</td>
            <td>0</td>
            <td>135</td>
          </tr>
          <tr>
            <td>GOES</td>
            <td>17</td>
            <td>0</td>
            <td>17</td>
          </tr>
          <tr>
            <td>Galileo</td>
            <td>28</td>
            <td>0</td>
            <td>28</td>
          </tr>
          <tr>
            <td>Geodetic</td>
            <td>49</td>
            <td>0</td>
            <td>49</td>
          </tr>
          <tr>
            <td>Geostationary</td>
            <td>1013</td>
            <td>0</td>
            <td>1013</td>
          </tr>
          <tr>
            <td>Global Positioning System (GPS) Constellation</td>
            <td>75</td>
            <td>0</td>
            <td>75</td>
          </tr>
          <tr>
            <td>Global Positioning System (GPS) Operational</td>
            <td>31</td>
            <td>0</td>
            <td>31</td>
          </tr>
          <tr>
            <td>Globalstar</td>
            <td>85</td>
            <td>0</td>
            <td>85</td>
          </tr>
          <tr>
            <td>Glonass Constellation</td>
            <td>141</td>
            <td>0</td>
            <td>141</td>
          </tr>
          <tr>
            <td>Glonass Operational</td>
            <td>26</td>
            <td>0</td>
            <td>26</td>
          </tr>
          <tr>
            <td>Gonets</td>
            <td>21</td>
            <td>0</td>
            <td>21</td>
          </tr>
          <tr>
            <td>Gorizont</td>
            <td>33</td>
            <td>0</td>
            <td>33</td>
          </tr>
          <tr>
            <td>IRNSS</td>
            <td>8</td>
            <td>0</td>
            <td>8</td>
          </tr>
          <tr>
            <td>ISS</td>
            <td>17</td>
            <td>1</td>
            <td>18</td>
          </tr>
          <tr>
            <td>Intelsat</td>
            <td>90</td>
            <td>0</td>
            <td>90</td>
          </tr>
          <tr>
            <td>Iridium</td>
            <td>111</td>
            <td>0</td>
            <td>111</td>
          </tr>
          <tr>
            <td>Lemur</td>
            <td>85</td>
            <td>0</td>
            <td>85</td>
          </tr>
          <tr>
            <td>Military</td>
            <td>565</td>
            <td>4</td>
            <td>570</td>
          </tr>
          <tr>
            <td>Molniya</td>
            <td>36</td>
            <td>0</td>
            <td>36</td>
          </tr>
          <tr>
            <td>NOAA</td>
            <td>26</td>
            <td>0</td>
            <td>26</td>
          </tr>
          <tr>
            <td>Navy Navigation Satellite System</td>
            <td>37</td>
            <td>0</td>
            <td>37</td>
          </tr>
          <tr>
            <td>O3B Networks</td>
            <td>20</td>
            <td>0</td>
            <td>20</td>
          </tr>
          <tr>
            <td>OneWeb</td>
            <td>628</td>
            <td>0</td>
            <td>628</td>
          </tr>
          <tr>
            <td>Orbcomm</td>
            <td>61</td>
            <td>0</td>
            <td>61</td>
          </tr>
          <tr>
            <td>Parus</td>
            <td>95</td>
            <td>0</td>
            <td>95</td>
          </tr>
          <tr>
            <td>QZSS</td>
            <td>4</td>
            <td>0</td>
            <td>4</td>
          </tr>
          <tr>
            <td>Radar Calibration</td>
            <td>24</td>
            <td>0</td>
            <td>24</td>
          </tr>
          <tr>
            <td>Raduga</td>
            <td>44</td>
            <td>0</td>
            <td>44</td>
          </tr>
          <tr>
            <td>Russian LEO Navigation</td>
            <td>15</td>
            <td>0</td>
            <td>15</td>
          </tr>
          <tr>
            <td>Satellite-Based Augmentation System</td>
            <td>14</td>
            <td>0</td>
            <td>14</td>
          </tr>
          <tr>
            <td>Search & rescue</td>
            <td>16</td>
            <td>0</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Space & Earth Science</td>
            <td>528</td>
            <td>12</td>
            <td>540</td>
          </tr>
          <tr>
            <td>Starlink</td>
            <td>5731</td>
            <td>0</td>
            <td>5731</td>
          </tr>
          <tr>
            <td>Strela</td>
            <td>565</td>
            <td>0</td>
            <td>565</td>
          </tr>
          <tr>
            <td>TV</td>
            <td>410</td>
            <td>0</td>
            <td>410</td>
          </tr>
          <tr>
            <td>Tracking and Data Relay Satellite System</td>
            <td>23</td>
            <td>0</td>
            <td>23</td>
          </tr>
          <tr>
            <td>Tselina</td>
            <td>58</td>
            <td>0</td>
            <td>58</td>
          </tr>
          <tr>
            <td>Tsikada</td>
            <td>22</td>
            <td>0</td>
            <td>22</td>
          </tr>
          <tr>
            <td>Tsiklon</td>
            <td>28</td>
            <td>0</td>
            <td>28</td>
          </tr>
          <tr>
            <td>Weather</td>
            <td>111</td>
            <td>0</td>
            <td>111</td>
          </tr>
          <tr>
            <td>Westford Needles</td>
            <td>43</td>
            <td>0</td>
            <td>43</td>
          </tr>
          <tr>
            <td>XM and Sirius</td>
            <td>9</td>
            <td>0</td>
            <td>9</td>
          </tr>
          <tr>
            <td>Yaogan</td>
            <td>46</td>
            <td>0</td>
            <td>46</td>
          </tr>
        </tbody>
      </table>
    </div>
    </div>
  );
}

export default Data;
